### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by alexandre-mbm** [F123/F123-Visual#1]
Where I find instructions about using these scripts to build the distro?

**Comment by the-kyle** [comment]
The manjaro-tools package can be used to build the distro from the
profiles here once the migration is complete. For now, this repository
is in a state of flux while the necessary files are being reimported.
This was necessary to migrate to the new manjaro-tools build system.
Once the migration is complete and all files have been pushed back into
the repository, the buildiso man page should get you started. Also, the
manjaro-tools.conf file in the top level is well documented, and
provides more options not necessarily covered in buildiso.
